Select * from customer limit 5;


--Q1 What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

--Q2 Which customer used a discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3 Which are the top 5 product whit the highest average review rating

select item_purchased as "Products", ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 Compare the average Purchase Amount between Standerd and Express Shipping

select shipping_type, round(avg(purchase_amount),2) as Revenue
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5 Do subscribed customer spend more? compare average spend and total revenue between subscribed and non-subscribed customer

select subscription_status,
count(customer_id) as "Total Customer",
round(avg(purchase_amount),2) as "Average Purchase", 
sum(purchase_amount) as "Total Revenue"
from customer
group by subscription_status
order by "Average Purchase" desc;

--Q6  Which 5 Products have the highest percentage of purchases with discount applied ?

select item_purchased AS "Item Name", 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as "Discount Rate"
from customer 
group by item_purchased
order by "Discount Rate" desc
limit 5;

--Q7  Segment Customer into New, Returning, and Loyal Based on Their Total Number of previous Purchases, 
--and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 then 'New'
when previous_purchases between 2 and 15 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

--Q8 What is the top 3 purchased products within each category
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status as "Subscribe Status",
count(previous_purchases) as  "Repeated Customers"
from customer
where previous_purchases >= 6
group by "Subscribe Status"

--Q10 What is the revenue Contibutiom of each age Group

select age_group as "Age Group",
sum(purchase_amount) as  "Revenue"
from customer
group by "Age Group"
order by "Revenue" desc;
